#!name=ForOwnUse
#!desc=ForOwnUse
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/biliad.png
#!author=ddgksf2013






[Script]
# ✅ Spotify
biliad=type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js
# ✅ 酷我音乐(会员共享)[vip至2023-05-07]
biliad=type=http-response,pattern=^https?:\/\/.*(kuwo|lrts).*(music\.pay\?ne|\/a\.p|v\d\/api\/(user\/in|pay\/vi)|\w{3}\/v\d\/user\/vi|\w{3}\/spi\/ms|\w{3}\/v\d\/the|\w{3}\/enc\/use),requires-body=1,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/KuWoMusicProCrack.js
^https?:\/\/.*(kuwo|lrts).*(music\.pay\?ui),requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/KuWoMusicProCrack.js
# ✅ 一言(need登录)
biliad=type=http-response,pattern=^https:\/\/app\.yiyan\.art\/yiyan\/,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/YiYanProCrack.js
# ✅ 西窗烛(need登录)
biliad=type=http-response,pattern=^https://lchttpapi.xczim.com/*,requires-body=1,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/XiChuangZhuProCrack.js
# ✅ 简讯
biliad=type=http-response,pattern=^https?:\/\/api\.tipsoon\.com\/api\/v1\/user\/info,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/JianXunProCrack.js



#>>>>>>>>>>>>>>>>新闻类VIP
# ✅ 财新周刊
biliad=type=http-response,pattern=http://ipadcms.caixin.com/tmp/articles/*,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/CaiXinZhouKanProCrack.js




#>>>>>>>>>>>>>>>>图影类VIP
# ✅ 醒图(need登录)
biliad=type=http-response,pattern=^https:\/\/commerce-api\.faceu\.mobi\/commerce\/v1\/subscription,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/xt.js
# ✅ Fimo(need登录)
biliad=type=http-response,pattern=^https://server.yoyiapp.com/fimo-user/user$,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/FimoProCrack.js
# ✅ 傲软抠图(need登录)
biliad=type=http-response,pattern=^https?:\/\/.*\.aoscdn\.com\/base\/vip\/client\/authorizations$,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/ApowersoftProCrack.js
# ✅ 美图秀秀(need登录)
biliad=type=http-response,pattern=^https:\/\/api\.xiuxiu\.meitu\.com\/v1,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/mtxx.js
# ✅ 克拉壁纸
biliad=type=http-response,pattern=^https:\/\/claritywallpaper\.com\/clarity\/api\/(userInfo|special\/queryByCatalogAll|picture\/search|catalog\/listAll|top\/list|picture\/date\?date),requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/ClarityProCrack.js
# ✅ Picsart
biliad=type=http-response,pattern=^https?:\/\/api\.meiease\.cn\/shop\/subscription\/validate,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/PicsartProCrack.js
# ✅ 黄油相机
biliad=type=http-response,pattern=^https?:\/\/api4\.bybutter\.com\/v4\/(users\/me$|shop\/me\/privileges$),requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/BybutterProCrack.js



#>>>>>>>>>>>>>>>>工具类VIP
# ✅ TopWidgets
biliad=type=http-response,pattern=^https?:\/\/.*xiaozujian\.com\/api\/app\/config\/userConfig,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/TopwidgetsProCrack.js
# ✅ 百度网盘(倍速)
biliad=type=http-response,pattern=^https:\/\/pan\.baidu\.com\/rest\/\d\.\d\/membership\/user,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/BaiDuCloudProCrack.js
# ✅ Nicegram
biliad=type=http-response,pattern=^https?:\/\/restore-access\.indream\.app\/restoreAccess\?id=\d{5,10},requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/NicegramProCrack.js
# ✅ Appraven(美化)
biliad=type=http-response,pattern=^https?:\/\/appraven\.net\/AppRaven\/(app|social|buy),requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/AppravenProCrack.js
# ✅ 扫描全能王
biliad=type=http-response,pattern=^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?,requires-body=1,script-path=https://github.com/ddgksf2013/dev/raw/main/CamscannerProCrack.js

[mitm] 
hostname = %APPEND% commerce-api.faceu.mobi, api4.bybutter.com, wallpaper.soutushenqi.com, api.tipsoon.com, *xiaozujian, lchttpapi.xczim.com, app.yiyan.art, *kuwo*, *lrts*, gateway.caixin.com, notability.com, pan.baidu.com, spclient.wg.spotify.com, ticktick.com, ap*.intsig.net, ipadcms.caixin.com, server.yoyiapp.com, *.aoscdn.com, *.xiuxiu.meitu.com, claritywallpaper.com, api.meiease.cn, restore-access.indream.app, appraven.net
