##############################################
# > 如需引用请注明出处，谢谢合作！
# > https://t.me/ddgksf2013
# > Only for own use, created by ddgksf2013
# > 更新时间：2023-01-08
# > 以下APP解锁，适用【最新版】，墨鱼都已逐一测试其有效性
# > 仅支持旧版解锁的重写都已删除或已注释
# > https://github.com/ddgksf2013/dev/raw/master/ForOwnUse.conf
##############################################


[rewrite_local]
^https:\/\/commerce-api\.faceu\.mobi\/commerce\/v1\/subscription,requires-body=1,script-path=script-response-body https://github.com/ddgksf2013/dev/raw/main/XingTuProCrack.js

# ✅ Spotify
^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,script-path=
script-response-body https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js
# ✅ 酷我音乐(会员共享)[vip至2023-05-07]
^https?:\/\/.*(kuwo|lrts).*(music\.pay\?ne|\/a\.p|v\d\/api\/(user\/in|pay\/vi)|\w{3}\/v\d\/user\/vi|\w{3}\/spi\/ms|\w{3}\/v\d\/the|\w{3}\/enc\/use),requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/KuWoMusicProCrack.js
^https?:\/\/.*(kuwo|lrts).*(music\.pay\?ui),requires-body=1,script-path=
script-request-header https://github.com/ddgksf2013/dev/raw/main/KuWoMusicProCrack.js
# ✅ 一言(need登录)
^https:\/\/app\.yiyan\.art\/yiyan\/,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/YiYanProCrack.js
# ✅ 西窗烛(need登录)
https://lchttpapi.xczim.com/*,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/XiChuangZhuProCrack.js
# ✅ 简讯
^https?:\/\/api\.tipsoon\.com\/api\/v1\/user\/info,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/JianXunProCrack.js



#>>>>>>>>>>>>>>>>新闻类VIP
# ✅ 财新周刊
http://ipadcms.caixin.com/tmp/articles/*,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/CaiXinZhouKanProCrack.js




#>>>>>>>>>>>>>>>>图影类VIP
# ✅ 醒图(need登录)
^https?:\/\/(commerce.*api|pay)\.(faceu|wecut)\.(com|mobi)\/(commerce|apple)\/(iosAppVerifyReceipt\.php|v1\/subscription\/user_info),requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/XingTuProCrack.js
# ✅ Fimo(need登录)
^https://server.yoyiapp.com/fimo-user/user$,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/FimoProCrack.js
# ✅ 傲软抠图(need登录)
https?:\/\/.*\.aoscdn\.com\/base\/vip\/client\/authorizations$,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/ApowersoftProCrack.js
# ❌ 美图秀秀(need登录)
;^https:\/\/api\.xiuxiu\.meitu\.com\/v1,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/mtxx.js
# ✅ 克拉壁纸
^https:\/\/claritywallpaper\.com\/clarity\/api\/(userInfo|special\/queryByCatalogAll|picture\/search|catalog\/listAll|top\/list|picture\/date\?date),requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/ClarityProCrack.js
# ✅ Picsart
^https?:\/\/api\.meiease\.cn\/shop\/subscription\/validate,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/PicsartProCrack.js
# ✅ 搜图神器
http:\/\/wallpaper\.soutushenqi\.com\/api\/v1\/account\/token,requires-body=1,script-path=
response-body vipType": 0 response-body vipType": 1024
# ✅ 黄油相机
^https?:\/\/api4\.bybutter\.com\/v4\/(users\/me$|shop\/me\/privileges$),requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/BybutterProCrack.js



#>>>>>>>>>>>>>>>>工具类VIP
# ✅ TopWidgets
^https?:\/\/.*xiaozujian\.com\/api\/app\/config\/userConfig,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/TopwidgetsProCrack.js
# ✅ 百度网盘(倍速)
^https:\/\/pan\.baidu\.com\/rest\/\d\.\d\/membership\/user,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/BaiDuCloudProCrack.js
# ✅ Nicegram
https?:\/\/restore-access\.indream\.app\/restoreAccess\?id=\d{5,10},requires-body=1,script-path=
echo-response text/json echo-response https://github.com/ddgksf2013/dev/raw/main/NicegramProCrack.js
# ✅ Appraven(美化)
^https?:\/\/appraven\.net\/AppRaven\/(app|social|buy),requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/AppravenProCrack.js
# ✅ 扫描全能王
^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?,requires-body=1,script-path=
script-response-body https://github.com/ddgksf2013/dev/raw/main/CamscannerProCrack.js

[mitm] 
hostname = *faceu*, api4.bybutter.com, wallpaper.soutushenqi.com, api.tipsoon.com, *xiaozujian, lchttpapi.xczim.com, app.yiyan.art, *kuwo*, *lrts*, gateway.caixin.com, notability.com, pan.baidu.com, spclient.wg.spotify.com, ticktick.com, ap*.intsig.net, ipadcms.caixin.com, server.yoyiapp.com, *.aoscdn.com, *.xiuxiu.meitu.com, claritywallpaper.com, api.meiease.cn, restore-access.indream.app, appraven.net