#!name=影视网站去广告
#!desc=@ddgksf2013
#!icon=https://raw.githubusercontent.com/Tartarus2014/For-own-use/master/Color/EMBY.png

#// ==UserScript==
#// @ScriptName        影视网站去广告
#// @Author            @ddgksf2013
#// @ForHelp           若有屏蔽广告的需求，可公众号后台回复网页链接
#// @WechatID          公众号墨鱼手记
#// @TgChannel         https://t.me/ddgksf2021
#// @Contribute        https://t.me/ddgksf2013_bot
#// @Feedback          📮 ddgksf2013@163.com 📮
#// @Attention         如需引用请注明出处，谢谢合作！
#// @UpdateTime        2022-12-08
#// @Function          自用影视网站去广告配置（不定期更新）
#// @Suitable          自行观看"# > "注释内容
#// @Explain           推荐使用手机版Chrome或Alook浏览器(仅供墨鱼本人及小部分QX用户使用)
#// @ScriptURL         https://github.com/ddgksf2013/Rewrite/raw/master/Html/WebAdBlock.conf

[MITM]
hostname = %APPEND%  *netflix*, *bdys*,cupfox.app,*cokemv*,*pornhub.com,*lezhutv*,*bimi*,18comic.org,*5y*,*gimytv*,*tkznp*,*czspp*,*ikandy*,*libvio*


[URL Rewrite]
^https:\/\/(cn|www)\.pornhub\.com\/_xa\/ads - reject-dict



[Script]
# > 14 奈飞鸭[网页优化]@ddgksf2013 - 网站地址：https://yanetflix.com
奈飞鸭=type=http-response,pattern=^https?:\/\/.*netflix.*\/($|[0-9a-zA-Z=_/-]+\.html$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/netflix.js

# > 13 哔嘀影视[网页优化]@ddgksf2013 - 网站地址：https://www.bdys01.com 
哔嘀影视=type=http-response,pattern=^https?:\/\/.*bdys.*com\/($|([a-z]+)\/(play\/)?\d+.*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/bdys.js

# > 12 茶杯狐[网页优化]@ddgksf2013 - 网站地址：https://cupfox.app
茶杯狐=type=http-response,pattern=^https?:/\/cupfox\.app\/($|(search|list|s|_next).*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/cupbox.js

# > 11 Cokemv[网页优化]@ddgksf2013 - 网站地址：https://cokemv.me 
Cokemv=type=http-response,pattern=^https?:/\/cokemv\.me\/($|vod.*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/cokemv.js

# > 10 PornHub[网页优化]@ddgksf2013 - 网站地址：https://cn.pornhub.com
PornHub=type=http-response,pattern=^https?:/\/(cn|www)\.pornhub\.com\/($|(view|video).*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/pornhub.js

# > 09 LeZhu[网页优化]@ddgksf2013 - 网站地址：http://www.lezhutv.com
PornHub=type=http-response,pattern=^https?:/\/.*lezhutv\.com\/($|(type|detail|play|index).*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/lezhu.js

# > 08 Bimi[网页优化]@ddgksf2013 - 网站地址：https://www.bimi.net
Bimi=type=http-response,pattern=^https?:/\/.*bimi.*net\/($|(vodshow|bangumi|type)\/[0-9a-z-\/]+\/$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/bimi.js

# > 07 禁漫天堂[网页优化]@ddgksf2013 - 网站地址：https://18comic.org
禁漫天堂=type=http-response,pattern=^https?:\/\/.*18comic\.org\/($|(album|photo).*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/18comic.js

# > 06 555影视[网页优化]@ddgksf2013 - 网站地址：https://555yy6.com
555影视=type=http-response,pattern=^https?:\/\/.*5y.*\/($|[0-9a-zA-Z=_/-]+\.html$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/555.js

# > 05 剧迷[网页优化]@ddgksf2013 - 网站地址：https://gimytv.app
剧迷=type=http-response,pattern=^https?:\/\/.*gimytv.*\/($|[0-9a-zA-Z=_/-]+\.html$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/gimytv.js

# > 04 天空影视[网页优化]@ddgksf2013 - 网站地址：https://tkznp.com/ ****
天空影视=type=http-response,pattern=^https?:\/\/.*tkznp.*com\/($|[0-9a-zA-Z=_/-]+\.html$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/tkys.js

# > 03 厂长电影[网页优化]@ddgksf2013 - 网站地址：https://www.czspp.com/
厂长电影=type=http-response,pattern=^https?:/\/.*czspp.*com\/($|\?btwaf=\w+$|[0-9a-zA-Z=_/-]+\.html),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/qianoo.js

# > 02 真不卡[网页优化]@ddgksf2013 - 网站地址：https://www.ikandy.fun
真不卡=type=http-response,pattern=^https?:\/\/.*ikandy.*fun\/($|(vod|top).*$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/zhenbuka.js

# > 01 libvio[网页优化]@ddgksf2013 - 网站地址：https://www.iioo.me
libvio=type=http-response,pattern=^https?:\/\/.*libvio.*me\/($|[0-9a-zA-Z=_/-]+\.html$),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/libvio.js